import { useFeatureStorage } from "@/hooks/use-feature-storage";

interface Person { name: string; emoji: string; busy: string; }
const DEFAULT_PEOPLE: Person[] = [
  { name: "You", emoji: "🧑", busy: "" },
  { name: "Alex", emoji: "👩‍💻", busy: "" },
  { name: "Sam", emoji: "🧔", busy: "" },
];
const HOURS = Array.from({ length: 12 }, (_, i) => i + 8);

export default function MultiPersonScheduler() {
  const { state, setState } = useFeatureStorage("multi-person-scheduler", { people: DEFAULT_PEOPLE, result: null as string[] | null, stats: { runs: 0, successes: 0 } });
  const toMin = (t: string) => { const [h, m] = t.split(":").map(Number); return (h || 0) * 60 + (m || 0); };
  const isBusy = (person: Person, hour: number) => person.busy.split(",").map((s) => s.trim()).filter(Boolean).some((slot) => { const parts = slot.split("-"); if (parts.length !== 2) return false; const bs = toMin(parts[0]), be = toMin(parts[1]); return hour * 60 < be && (hour + 1) * 60 > bs; });
  const findFree = () => { const free: string[] = []; HOURS.forEach((h) => { if (state.people.every((p) => !isBusy(p, h))) free.push(`${h > 12 ? h - 12 : h}:00 ${h >= 12 ? "PM" : "AM"}`); }); setState((prev) => ({ ...prev, result: free, stats: { runs: prev.stats.runs + 1, successes: prev.stats.successes + (free.length > 0 ? 1 : 0) } })); };
  const updateBusy = (idx: number, val: string) => setState((prev) => ({ ...prev, people: prev.people.map((p, i) => (i === idx ? { ...p, busy: val } : p)), result: null }));
  const addPerson = () => { const emojis = ["👨‍🎨", "👩‍🔬", "🧑‍🚀", "👨‍🍳", "👩‍🎤"]; setState((prev) => ({ ...prev, people: [...prev.people, { name: `Person ${prev.people.length + 1}`, emoji: emojis[prev.people.length % emojis.length], busy: "" }] })); };
  return <div className="bg-card p-8 md:p-10 border-[3px] border-sunny-yellow overflow-hidden" style={{ borderRadius: "2rem 1rem 2rem 1rem", boxShadow: "0 0 20px hsla(49, 100%, 65%, 0.5)" }}><h2 className="font-display text-3xl md:text-4xl text-gradient-lime-yellow mb-2 text-center">👥 MULTI-PERSON SCHEDULER</h2><p className="text-sm text-muted-foreground text-center mb-4">Find when EVERYONE is free!</p><div className="space-y-3 mb-4">{state.people.map((p, i) => <div key={i} className="flex items-center gap-2"><span className="text-2xl">{p.emoji}</span><input className="chrono-input flex-1 text-sm" placeholder="09:00-10:00, 14:00-15:00" value={p.busy} onChange={(e) => updateBusy(i, e.target.value)} /></div>)}{state.people.length < 6 && <button onClick={addPerson} className="text-sm text-neon-cyan font-bold hover:underline w-full text-center">+ ADD PERSON</button>}</div><div className="mb-4 overflow-x-auto"><div className="grid gap-px" style={{ gridTemplateColumns: `60px repeat(${HOURS.length}, 1fr)` }}><div />{HOURS.map((h) => <div key={h} className="text-center text-xs font-display text-muted-foreground">{h > 12 ? h - 12 : h}{h >= 12 ? "p" : "a"}</div>)}{state.people.map((p, i) => <div key={i} className="contents"><div className="text-xs font-bold flex items-center gap-1">{p.emoji}</div>{HOURS.map((h) => <div key={`${i}-${h}`} className={`h-6 rounded-sm transition-all ${isBusy(p, h) ? "bg-electric-pink/50 border border-electric-pink/70" : "bg-lime-green/20 border border-lime-green/30"}`} />)}</div>)}</div></div><button onClick={findFree} className="btn-3d-lime w-full py-3 font-display text-xl tracking-wider rounded-lg hover:animate-jiggle">🔍 WHEN ARE WE ALL FREE?</button>{state.result && <div className="mt-4 text-center animate-bounce-in">{state.result.length > 0 ? <div className="comic-bubble"><p className="font-display text-lg mb-1">🎉 ALL FREE AT:</p><div className="flex flex-wrap gap-2 justify-center">{state.result.map((t) => <span key={t} className="bg-lime-green/30 text-foreground px-2 py-1 rounded-full text-sm font-bold border border-lime-green/50">{t}</span>)}</div></div> : <div className="comic-bubble !bg-electric-pink !text-foreground !border-foreground font-display text-lg">😱 NO COMMON FREE TIME! TRY RESCHEDULING!</div>}</div>}</div>;
}
